FROM ubuntu:20.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -q -y install net-tools iproute2 iputils-ping openssh-server python3 python3-pip sudo -y
RUN pip3 install --upgrade pip
RUN pip3 install paramiko requests urllib3 scp
RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo -u 1000 user
RUN sed -i "s/.*PermitRootLogin.*/PermitRootLogin yes/g" /etc/ssh/sshd_config
RUN echo 'user:pass' | chpasswd
RUN service ssh start

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]