FROM ubuntu:bionic

RUN apt-get update && apt-get install openssh-server python3 python3-pip sudo -y
RUN pip3 install paramiko requests
RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo -u 1000 user
RUN sed -i "s/.*PermitRootLogin.*/PermitRootLogin yes/g" /etc/ssh/sshd_config
RUN echo 'user:pass' | chpasswd
RUN service ssh start

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]